
"""Serena VS Code Builder CLI."""

from __future__ import annotations

import click
from rich.console import Console

from openjarvis.tools.serena_vscode_builder import (
    SerenaVSCodeBuilderFinalCheckTool,
    SerenaVSCodeBuilderStatusTool,
    SerenaVSCodeBuilderTemplatesTool,
    SerenaVSCodeBuilderScaffoldTool,
    SerenaVSCodeBuilderBuildWordPressSectionTool,
    SerenaVSCodeBuilderBuildReactComponentTool,
    SerenaVSCodeBuilderInspectBuildTool,
    SerenaVSCodeBuilderBuildSectionTool,
    SerenaVSCodeBuilderPlanTool,
)


@click.group("vscode-builder")
def vscode_builder() -> None:
    """Native Serena VS Code Builder tools."""


@vscode_builder.command("status")
def status() -> None:
    """Show Serena VS Code Builder status."""
    console = Console()
    result = SerenaVSCodeBuilderStatusTool().execute()
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


@vscode_builder.command("templates")
def templates() -> None:
    """List available builder templates."""
    console = Console()
    result = SerenaVSCodeBuilderTemplatesTool().execute()
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


@vscode_builder.command("final-check")
@click.option("--root", required=True, help="Approved root alias.")
@click.option("--module", default="openjarvis.tools.serena_vscode_builder", help="Module import to check.")
def final_check(root: str, module: str) -> None:
    """Run builder final local check."""
    console = Console()
    result = SerenaVSCodeBuilderFinalCheckTool().execute(root=root, module=module)
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


@vscode_builder.command("plan")
@click.option("--root", required=True, help="Approved root alias.")
@click.option("--name", required=True, help="Build name.")
@click.option("--goal", required=True, help="Build goal.")
@click.option("--kind", default="feature-scaffold", help="Build kind/template.")
@click.option("--target-path", default="", help="Relative target path.")
def plan(root: str, name: str, goal: str, kind: str, target_path: str) -> None:
    """Create a build plan without writing project files."""
    console = Console()
    result = SerenaVSCodeBuilderPlanTool().execute(
        root=root,
        name=name,
        goal=goal,
        kind=kind,
        target_path=target_path,
    )
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


@vscode_builder.command("scaffold")
@click.option("--root", required=True, help="Approved root alias.")
@click.option("--name", required=True, help="Feature name.")
@click.option("--target-path", required=True, help="Relative target folder.")
@click.option("--kind", default="python", help="Feature kind.")
@click.option("--overwrite", is_flag=True, help="Overwrite existing files.")
def scaffold(root: str, name: str, target_path: str, kind: str, overwrite: bool) -> None:
    """Scaffold a feature folder with source, test, and docs."""
    console = Console()
    result = SerenaVSCodeBuilderScaffoldTool().execute(
        root=root,
        name=name,
        target_path=target_path,
        kind=kind,
        overwrite=overwrite,
    )
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


@vscode_builder.command("build-section")
@click.option("--root", required=True, help="Approved root alias.")
@click.option("--target-path", required=True, help="Relative target folder.")
@click.option("--title", required=True, help="Section title.")
@click.option("--subtitle", default="A polished website section generated by Serena.", help="Section subtitle.")
@click.option("--cta-text", default="Get started", help="CTA text.")
@click.option("--cta-url", default="#", help="CTA URL.")
@click.option("--overwrite", is_flag=True, help="Overwrite existing files.")
def build_section(root: str, target_path: str, title: str, subtitle: str, cta_text: str, cta_url: str, overwrite: bool) -> None:
    """Build a polished HTML/CSS website section."""
    console = Console()
    result = SerenaVSCodeBuilderBuildSectionTool().execute(
        root=root,
        target_path=target_path,
        title=title,
        subtitle=subtitle,
        cta_text=cta_text,
        cta_url=cta_url,
        overwrite=overwrite,
    )
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


@vscode_builder.command("build-wordpress-section")
@click.option("--root", required=True, help="Approved root alias.")
@click.option("--target-path", required=True, help="Relative target folder.")
@click.option("--title", required=True, help="Section title.")
@click.option("--subtitle", default="A WordPress-ready section generated by Serena.", help="Section subtitle.")
@click.option("--cta-text", default="Book now", help="CTA text.")
@click.option("--cta-url", default="#", help="CTA URL.")
@click.option("--overwrite", is_flag=True, help="Overwrite existing files.")
def build_wordpress_section(root: str, target_path: str, title: str, subtitle: str, cta_text: str, cta_url: str, overwrite: bool) -> None:
    """Build a WordPress-ready HTML section."""
    console = Console()
    result = SerenaVSCodeBuilderBuildWordPressSectionTool().execute(
        root=root,
        target_path=target_path,
        title=title,
        subtitle=subtitle,
        cta_text=cta_text,
        cta_url=cta_url,
        overwrite=overwrite,
    )
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


@vscode_builder.command("build-react-component")
@click.option("--root", required=True, help="Approved root alias.")
@click.option("--target-path", required=True, help="Relative target folder.")
@click.option("--name", required=True, help="Component name.")
@click.option("--title", default="", help="Component title.")
@click.option("--subtitle", default="", help="Component subtitle.")
@click.option("--cta-text", default="Get started", help="CTA text.")
@click.option("--cta-url", default="#", help="CTA URL.")
@click.option("--overwrite", is_flag=True, help="Overwrite existing files.")
def build_react_component(root: str, target_path: str, name: str, title: str, subtitle: str, cta_text: str, cta_url: str, overwrite: bool) -> None:
    """Build a React component."""
    console = Console()
    result = SerenaVSCodeBuilderBuildReactComponentTool().execute(
        root=root,
        target_path=target_path,
        name=name,
        title=title,
        subtitle=subtitle,
        cta_text=cta_text,
        cta_url=cta_url,
        overwrite=overwrite,
    )
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


@vscode_builder.command("inspect-build")
@click.option("--root", required=True, help="Approved root alias.")
@click.option("--target-path", required=True, help="Relative build folder.")
@click.option("--limit", default=100, type=int, help="Maximum files to inspect.")
def inspect_build(root: str, target_path: str, limit: int) -> None:
    """Inspect generated build files."""
    console = Console()
    result = SerenaVSCodeBuilderInspectBuildTool().execute(
        root=root,
        target_path=target_path,
        limit=limit,
    )
    console.print(result.content if result.success else f"[red]{result.content}[/red]")


__all__ = ["vscode_builder"]
