[supervisord]
nodaemon=true

[program:jarvis]
directory=/app
command=uvicorn start:app --host 127.0.0.1 --port 5173 --workers 2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
