from pathlib import Path

ROOT = Path.cwd()
tool_path = ROOT / "src" / "openjarvis" / "tools" / "serena_hub.py"
cli_path = ROOT / "src" / "openjarvis" / "cli" / "hub_cmd.py"

tool = tool_path.read_text(encoding="utf-8")
cli = cli_path.read_text(encoding="utf-8")

insert_before = tool.index("def hub_execution_runner_plan(")

batch8_functions = r'''
def _find_latest_runner_plan_for_approval(approval_id: str) -> dict[str, Any] | None:
    runner_root = HUB_ROOT / "execution-runner-plans"
    if not runner_root.exists():
        return None

    candidates: list[dict[str, Any]] = []
    for path in sorted(runner_root.glob("*.json")):
        payload = _safe_read_json(path)
        if isinstance(payload, dict) and payload.get("approval_id") == approval_id:
            payload["_path"] = str(path).replace("\\", "/")
            candidates.append(payload)

    if not candidates:
        return None

    return sorted(candidates, key=lambda item: item.get("timestamp", ""), reverse=True)[0]


def hub_patch_prep(
    approval_id: str,
    patch_name: str = "serena_hub_patch",
    draft_only: bool = True,
) -> dict[str, Any]:
    """Create a draft patch-prep artifact for an approved runner plan.

    This never executes code, modifies source files, commits, pushes,
    installs dependencies, or reads/exports secrets.
    """
    _ensure_base_state()

    runner_plan = _find_latest_runner_plan_for_approval(approval_id)
    if runner_plan is None or runner_plan.get("status") != "runner_plan_ready":
        payload = {
            "status": "blocked",
            "reason": "No ready runner plan exists for this approval.",
            "approval_id": approval_id,
            "patch_name": patch_name,
            "draft_only": draft_only,
            "source_files_modified": False,
            "patch_script_executed": False,
            "execution_performed": False,
            "external_action_taken": False,
            "timestamp": _utc_now(),
        }
        path = HUB_ROOT / "patch-prep" / f"blocked_patch_prep_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
        _write_json(path, payload)
        hub_blocked_unapproved_action(
            action=f"patch_prep_without_ready_runner_plan:{approval_id}",
            operator="hub",
            reason=payload["reason"],
        )
        return payload

    safe_name = "".join(ch if ch.isalnum() or ch in {"_", "-"} else "_" for ch in patch_name).strip("_") or "serena_hub_patch"
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    prep_root = HUB_ROOT / "patch-prep"
    prep_root.mkdir(parents=True, exist_ok=True)

    draft_script_path = prep_root / f"{stamp}_{safe_name}_draft.py"

    draft_lines = [
        '"""Draft patch script for Serena Hub.',
        "",
        "Generated by:",
        "  serena hub patch-prep",
        "",
        f"Approval: {approval_id}",
        "",
        "Status:",
        "  DRAFT ONLY. Do not run until Kyle explicitly approves final execution.",
        "",
        "Safety:",
        "  - This script currently contains no source mutations.",
        "  - Add exact approved edits only after reviewing the runner plan.",
        "  - Run local secret scans before commit.",
        "  - Run the declared smoke test.",
        "  - Inspect git diff before commit.",
        '"""',
        "",
        "from pathlib import Path",
        "",
        "ROOT = Path.cwd()",
        f'APPROVAL_ID = "{approval_id}"',
        "DRAFT_ONLY = True",
        "",
        "def main() -> None:",
        '    print("[DRAFT] Patch script prepared for approval:", APPROVAL_ID)',
        '    print("[DRAFT] No source files modified.")',
        '    print("[DRAFT] Add approved patch operations here only after final explicit approval.")',
        "",
        'if __name__ == "__main__":',
        "    main()",
        "",
    ]
    draft_script_path.write_text("\n".join(draft_lines), encoding="utf-8")

    payload = {
        "status": "patch_prep_ready",
        "approval_id": approval_id,
        "patch_name": safe_name,
        "runner_plan": runner_plan,
        "draft_patch_script": str(draft_script_path).replace("\\", "/"),
        "draft_only": draft_only,
        "source_files_modified": False,
        "patch_script_executed": False,
        "execution_performed": False,
        "external_action_taken": False,
        "blocked_until_final_explicit_command": True,
        "required_before_final_execution": [
            "review draft patch script",
            "confirm exact approved file edits",
            "run local secret scan",
            "run smoke test after applying patch",
            "inspect git diff",
            "commit only approved source files",
            "push only after clean final status",
        ],
        "timestamp": _utc_now(),
    }

    path = prep_root / f"patch_prep_{stamp}_{safe_name}.json"
    _write_json(path, payload)

    hub_orb_state(
        orb_state="approval",
        active_operator="hub",
        active_task=f"Patch prep ready for review: {approval_id}",
        active_section="safety",
    )

    hub_activity_event(
        operator="hub",
        event_type="patch_prep",
        message=f"Draft patch prep created for approval {approval_id}. No execution performed.",
        status="patch_prep_ready",
        artifact_path=str(path).replace("\\", "/"),
    )

    hub_web_sync_data()
    return payload


def hub_patch_prep_list(status: str = "all") -> dict[str, Any]:
    """List patch-prep artifacts. No execution occurs."""
    prep_root = HUB_ROOT / "patch-prep"
    items: list[dict[str, Any]] = []

    if prep_root.exists():
        for path in sorted(prep_root.glob("patch_prep_*.json")):
            payload = _safe_read_json(path)
            if isinstance(payload, dict):
                payload["_path"] = str(path).replace("\\", "/")
                items.append(payload)

    if status != "all":
        items = [item for item in items if item.get("status") == status]

    return {
        "status": "listed",
        "filter": status,
        "patch_prep_count": len(items),
        "items": items,
        "execution_performed": False,
        "external_action_taken": False,
        "timestamp": _utc_now(),
    }


'''

if "def hub_patch_prep(" not in tool:
    tool = tool[:insert_before] + batch8_functions + tool[insert_before:]

for name in ["hub_patch_prep", "hub_patch_prep_list"]:
    if f'"{name}",' not in tool:
        tool = tool.replace('    "hub_execution_runner_plan",\n', f'    "{name}",\n    "hub_execution_runner_plan",\n')

tool_path.write_text(tool, encoding="utf-8")

for name in [
    "    hub_patch_prep,\n",
    "    hub_patch_prep_list,\n",
]:
    if name not in cli:
        cli = cli.replace("    hub_operator_rollup,\n", "    hub_operator_rollup,\n" + name)

marker = '@hub.command("execution-runner-plan")\n@click.option("--approval-id", required=True)\n'
commands = '''@hub.command("patch-prep")
@click.option("--approval-id", required=True)
@click.option("--patch-name", default="serena_hub_patch")
def patch_prep(approval_id, patch_name):
    """Create draft patch-prep artifact for approved runner plan. No execution occurs."""
    _print(
        hub_patch_prep(
            approval_id=approval_id,
            patch_name=patch_name,
            draft_only=True,
        )
    )


@hub.command("patch-prep-list")
@click.option("--status", "prep_status", default="all")
def patch_prep_list(prep_status):
    """List patch-prep artifacts. No execution occurs."""
    _print(hub_patch_prep_list(status=prep_status))


'''

if '@hub.command("patch-prep")' not in cli:
    cli = cli.replace(marker, commands + marker)

cli_path.write_text(cli, encoding="utf-8")

print("[OK] Patched Serena Hub Batch 8 patch-prep scaffold")
print("[OK] Added patch-prep and patch-prep-list")